# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    #Dotnet Microservice
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   run: dotnet restore SpotifyLike/SpotifyLike.sln
    # - name: Build
    #   run: dotnet build --no-restore SpotifyLike/SpotifyLike.sln
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal SpotifyLike/SpotifyLike.sln
    - name: Change Directory
      run: |
        cd ./SpotifyLike
        ls -a
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.REGISTRY_LOGIN_SERVER}}
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
    - name: Builder image and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{secrets.REGISTRY_LOGIN_SERVER}}/spotifylike-dotnet:${{github.sha}}
        file: ./SpotifyLike.API/Dockerfile
        context: .

